---
driver:
  name: docker

provisioner:
  name: chef_solo
  log_level: info

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[jemalloc::default]
      - recipe[openresty::default]
      - recipe[openresty::luarocks]
    attributes:
      openresty:
          default_site_enabled: true
          link_to_jemalloc: true
          luarocks:
              default_rocks:
                  luaproc: '1.0-3'
